catalog-pim:
    image : lcfumes/alpine-nginx-nodejs:0.0.1
    ports:
        - "80:80"
        - "8080:80"
    environment:
       - VIRTUAL_HOST=track.dafiti.dev
    volumes:
        - ./containers/web/nginx.conf:/etc/nginx/nginx.conf
        - ./containers/web/track.conf:/etc/nginx/sites-enabled/track.conf
        - ./dist:/srv/www/
